const CHARACTERDATA = {
    race: {
        altmer: "Altmer",
        argonian: "Argonian",
        bosmer: "Bosmer",
        breton: "Breton",
        dunmer: "Dunmer",
        imperial: "Imperial",
        khajiit: "Khajiit",
        nord: "Nord",
        orsimer: "Orsimer",
        redguard: "Redguard",
    },
    skill: {
        alchemy: "Alchemy",
        alteration: "Alteration",
        archery: "Archery",
        block: "Block",
        conjuration: "Conjuration",
        destruction: "Destruction",
        enchanting: "Enchanting",
        heavyArmor: "Heavy Armor",
        illusion: "Illusion",
        lightArmor: "Light Armor",
        lockpicking: "Lockpicking",
        oneHanded: "One-handed",
        pickpocket: "Pickpocket",
        restoration: "Restoration",
        smithing: "Smithing",
        sneak: "Sneak",
        speech: "Speech",
        twoHanded: "Two-handed",
    },
    faction: {
        bardsCollege: "Bards College",
        blades: "Blades",
        collegeWinterhold: "College of Winterhold",
        companions: "The Companions",
        darkBrotherhood: "Dark Brotherhood",
        dawnguard: "Dawnguard",
        imperialArmy: "Imperial Army",
        stormcloak: "Stormcloaks",
        thievesGuild: "Thieves Guild",
        vampires: "Volkihar Vampires",
    },
    follower: {
        assassin: "Assassin",
        barbarian: "Barbarian",
        bard: "Bard",
        creature: "Creature",
        lydia: "Lydia",
        mage: "Mage",
        nightblade: "Nightblade",
        none: "No Follower",
        miner: "Miner",
        priest: "Priest",
        ranger: "Ranger",
        sameRace: "Same Race as You",
        spellsword: "Spellsword",
        thief: "Thief",
        vampire: "Vampire",
        warrior: "Warrior",
    }
};

export default CHARACTERDATA;